name: Create Pull Request with Markdown

on:
  workflow_run:
    workflows: ["Generate Markdown"]
    types:
      - completed
    repositories:
      - thutuva/personal-tuva-test

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
