name: Download Markdown Artifact

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-second-repo

jobs:
  download_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifact
        run: |
          mkdir -p $GITHUB_WORKSPACE/.github
          curl -o .github/output.md -H "Authorization: Bearer ${{ secrets.GENERATE_MARKDOWN_TOKEN }}" \
          -L https://api.github.com/repos/thutuva/personal-tuva-test/actions/artifacts/mardown-artifact/zip
